apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: lifecore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: viktorsirakov08/lifecore-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: jwt
            - name: ConnectionString
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: connection-string
          envFrom:
            - configMapRef:
                name: backend-config